External api integration
wolox-training/dav-rails pull request #6
Opened 2021-06-01 22:13 UTC by daniel-vega-86

## Summary

[Change!] 
- Install httparty
- add books route
- create books controller
- create books service

## Screenshots

[Change!] N/A.

## Trello Card

[Change!] https://trello.com/c/Pi1mwZyw/34-2-integraci%C3%B3n-api-externa

2021-06-01 22:27 UTC, blacksam07 approved these changes

2021-06-01 22:27 UTC, blacksam07 commented on app/services/books_service.rb
> +  base_uri 'openlibrary.org'
use credentials in this case, read this article https://blog.saeloun.com/2019/10/10/rails-6-adds-support-for-multi-environment-credentials.html

2021-06-01 22:27 UTC, blacksam07 commented on config/routes.rb
> +  resources :books do
Use the resources crud method read this https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions
like 
```ruby
resources :books, only: :show
```

2021-06-01 22:27 UTC, blacksam07 commented on app/services/books_service.rb
> +    JSON.parse(book.body)[isbn].keep_if { |k, _| keys.include?(k) }
❤️

2021-06-01 22:27 UTC, blacksam07 requested changes
little changes

2021-06-02 00:27 UTC, redwarewolf requested changes

2021-06-02 00:27 UTC, redwarewolf commented on app/services/books_service.rb
> +    book = self.class.get('/api/books', options)
The route can be saved in a constant preferrably

2021-06-02 00:27 UTC, redwarewolf commented on app/services/books_service.rb
> +    JSON.parse(book.body)[isbn].keep_if { |k, _| keys.include?(k) }
Use Slice for this, but nice idea.

2021-06-02 00:27 UTC, redwarewolf commented on app/services/books_service.rb
> +    JSON.parse(book.body)[isbn].keep_if { |k, _| keys.include?(k) }
https://apidock.com/rails/Hash/slice

2021-06-02 18:20 UTC, blacksam07 approved these changes

2021-06-02 18:20 UTC, blacksam07 commented on app/services/books_service.rb
> +    path = '/api/books'
move at constant class outside the method, and include `/api` in base_uri
```ruby
BOOKS_PATH = '/books'.freeze # the freeze method locks editing
```

2021-06-02 18:20 UTC, blacksam07 commented on app/services/books_service.rb
> +    JSON.parse(book.body)[id].deep_symbolize_keys.slice(*keys)
move this logic to another method like at `process_response` the function of find_book method is only find not process a data

2021-06-02 18:20 UTC, blacksam07 commented on config/routes.rb
> +  resources :books, only: :show
since you are finding the book by ISBN, you can change the parameter
```ruby
resources :books, only: :show, param: :isbn
```

2021-06-02 20:00 UTC, blacksam07 approved these changes

2021-06-03 00:42 UTC, redwarewolf approved these changes

2021-06-03 13:26 UTC, merged